<script>
    import Bar from "$lib/component/d3/Bar.svelte";
    $: asset_data = [
        {
            id: 1,
            name: "Apple Inc",
            asset_type: "Equity",
            currency: "USD",
            nominale: 50000,
            kurs_iw: 287.05,
            kurs_fw: 13070822,
            exposure: 13070822,
            rendite: 0.3,
            component_var: 160238,
            var: 345008,
            liquidity_risk: 130708,
            country: "USA",
            sector: "IT",
        },
        {
            id: 2,
            name: "Wellsitin AG",
            asset_type: "Equity",
            currency: "EUR",
            nominale: 12042700,
            kurs_iw: 0.725,
            kurs_fw: 8730958,
            exposure: 8730958,
            rendite: 0.1,
            component_var: 929887,
            var: 1161244,
            liquidity_risk: 130964,
            country: "Deutschland",
            sector: "Finanzen",
        },
        {
            id: 3,
            name: "Cooperative Rabobank UA",
            asset_type: "FRN",
            currency: "EUR",
            nominale: 4000000,
            kurs_iw: 100.501,
            kurs_fw: 3922120,
            exposure: 3922120,
            rendite: 1.9,
            component_var: -1806,
            var: 1620,
            liquidity_risk: 12557,
            country: "Frankreich",
            sector: "Finanzen",
        },
        {
            id: 4,
            name: "Volksbank Wien AG",
            asset_type: "FRN",
            currency: "EUR",
            nominale: 4000000,
            kurs_iw: 98.503,
            kurs_fw: 3922120,
            exposure: 3922120,
            rendite: 3.4,
            component_var: -1017,
            var: 3139,
            liquidity_risk: 43501,
            country: "Österreich",
            sector: "Finanzen",
        },
        {
            id: 5,
            name: "Tsy Infl IX N/B",
            asset_type: "FRN",
            currency: "USD",
            nominale: 4000000,
            kurs_iw: 99.523,
            kurs_fw: 3625440,
            exposure: 3625440,
            rendite: 1.1,
            component_var: 18099,
            var: 68986,
            liquidity_risk: 5964,
            country: "USA",
            sector: "Basiskonsumgüter",
        },
        {
            id: 6,
            name: "Roche Holding AG-GS",
            asset_type: "Equity",
            currency: "CHF",
            nominale: 11000,
            kurs_iw: 314.95,
            kurs_fw: 3285338,
            exposure: 3285338,
            rendite: 2.3,
            component_var: 108060,
            var: 185681,
            liquidity_risk: 32853,
            country: "Schweiz",
            sector: "Basiskonsumgüter",
        },
        {
            id: 7,
            name: "Sriev NV",
            asset_type: "FRN",
            currency: "CHF",
            nominale: 3000000,
            kurs_iw: 101787,
            kurs_fw: 2895738,
            exposure: 2895738,
            rendite: 1.9,
            component_var: -5003,
            var: 11470,
            liquidity_risk: 14181,
            country: "Schweiz",
            sector: "IT",
        },
        {
            id: 8,
            name: "Credit Suisse AG London",
            asset_type: "Bond",
            currency: "GBP",
            nominale: 2500000,
            kurs_iw: 96.69,
            kurs_fw: 2778971,
            exposure: 2778971,
            rendite: 0.1,
            component_var: 15947,
            var: 53553,
            liquidity_risk: 21383,
            country: "UK",
            sector: "Finanzen",
        },
        {
            id: 9,
            name: "African Export-Import Bank",
            asset_type: "Bond",
            currency: "USD",
            nominale: 2500000,
            kurs_iw: 101.625,
            kurs_fw: 2330007,
            exposure: 2330007,
            rendite: 6.8,
            component_var: 6485,
            var: 38556,
            liquidity_risk: 19869,
            country: "USA",
            sector: "Finanzen",
        },
        {
            id: 10,
            name: "Aegon NV",
            asset_type: "FRN",
            currency: "EUR",
            nominale: 2000000,
            kurs_iw: 104.762,
            kurs_fw: 2095240,
            exposure: 2095240,
            rendite: 0.0,
            component_var: -1988,
            var: 1949,
            liquidity_risk: 18245,
            country: "Deutschland",
            sector: "IT",
        },
        {
            id: 11,
            name: "Telecom Italia Spa",
            asset_type: "Bond",
            currency: "EUR",
            nominale: 2000000,
            kurs_iw: 96148,
            kurs_fw: 1922960,
            exposure: 1922960,
            rendite: 6.8,
            component_var: -1432,
            var: 1795,
            liquidity_risk: 7846,
            country: "Italien",
            sector: "Telekommunikation",
        },
        {
            id: 12,
            name: "Bank of America Corp",
            asset_type: "FRN",
            currency: "USD",
            nominale: 2000000,
            kurs_iw: 95.07,
            kurs_fw: 1731605,
            exposure: 1731605,
            rendite: 0.0,
            component_var: 13847,
            var: 31040,
            liquidity_risk: 10278,
            country: "USA",
            sector: "Finanzen",
        },
        {
            id: 13,
            name: "GMP Quantis Low Volatile",
            asset_type: "Equity",
            currency: "EUR",
            nominale: 15000,
            kurs_iw: 112.22,
            kurs_fw: 1683300,
            exposure: 1683300,
            rendite: 1.6,
            component_var: 51523,
            var: 78679,
            liquidity_risk: 16833,
            country: "Deutschland",
            sector: "Andere",
        },
    ];
    let currencyResSorted;
    $: {
        // Sort the data by asset_type
        const sortedDataByCurrency = asset_data
            .slice()
            .sort((a, b) => a.currency.localeCompare(b.currency));

        // Calculate the sum of 'var' for each asset type
        const sumVarByCurrency =
            sortedDataByCurrency.reduce((acc, asset) => {
                const key = asset.currency;
                acc[key] = (acc[key] || 0) + asset.var;
                return acc;
            }, {});
        const currencyRes = Object.entries(sumVarByCurrency).map(
            ([key, value]) => ({
                key: key,
                value: value,
            }),
        );
        currencyResSorted = currencyRes
            .slice()
            .sort((a, b) => b.value - a.value);
    }
</script>
<Bar data={currencyResSorted}></Bar>